src/Foment/GestioBundle/Entity/Apunt.php
<?php 
// src/Foment/GestioBundle/Entity/Apunt.php
namespace Foment\GestioBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Foment\GestioBundle\Controller\UtilsController;

/**
 * @ORM\Entity
 * @ORM\Table(name="apunts")
 */
class Apunt
{
	
	/**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    
    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $num;		// Reset anual MAX $num de l'any en curs
    
    /**
     * @ORM\Column(type="datetime", nullable=false)
     */
    protected $dataapunt;		
    
    /**
     * @ORM\Column(type="string", length=1, nullable=false)
     */
    protected $tipus; // 'E' entrada o 'S' sortida
    
    /**
     * @ORM\Column(type="decimal", precision=6, scale=2, nullable=false)
     */
    protected $import;
    
    /**
     * @ORM\ManyToOne(targetEntity="ApuntConcepte")
     * @ORM\JoinColumn(name="concepte", referencedColumnName="id", nullable=false)
     */
    protected $concepte; 
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     */
    protected $observacions; 
    
    /**
     * @ORM\ManyToOne(targetEntity="Rebut")
     * @ORM\JoinColumn(name="rebut", referencedColumnName="id", nullable=true)
     */
    protected $rebut; // FK taula rebuts
    
    /**
     * @ORM\Column(type="datetime", nullable=false)
     */
    protected $dataentrada;
    
    /**
     * @ORM\Column(type="datetime", nullable=false)
     */
    protected $datamodificacio;
    
    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $databaixa;
   
    /**
     * Constructor
     */
    public function __construct($numapunt, $import = 0, $dataapunt = null, $tipus = UtilsController::TIPUS_APUNT_ENTRADA, 
    							$concepte = null, $rebut = null, $observacions = '')
    {
    	$this->id = 0;
    	$this->num = $numapunt;
    	if ($dataapunt == null) $this->dataapunt = new \DateTime('now');
    	else $this->dataapunt = $dataapunt;
    	$this->tipus = $tipus;
    	$this->import = $import;
    	$this->concepte = $concepte;
    	$this->observacions = $observacions;
    	$this->rebut = $rebut;
    	$this->dataentrada = new \DateTime();
    	$this->datamodificacio = new \DateTime();
    	
    }
    
    /**
     * Get num format
     *
     * @return String
     */
    public function getNumFormat()
    {
    	return str_pad($this->num, 6, '0', STR_PAD_LEFT) .'/'.$this->dataapunt->format('y');
    }
    
    /**
     * Està anul·lat l'apunt?
     *
     * @return boolean
     */
    public function anulat()
    {
    	return $this->databaixa != null;
    }
    
    /**
     * És sortida?
     *
     * @return boolean
     */
    public function esSortida()
    {
    	return $this->tipus == UtilsController::TIPUS_APUNT_SORTIDA;
    }
    
    /**
     * És entrada?
     *
     * @return boolean
     */
    public function esEntrada()
    {
    	return $this->tipus == UtilsController::TIPUS_APUNT_ENTRADA;
    }
    
    /**
     * Get concepte llarg 
     *
     * @return string
     */
    public function getConcepteLlarg()
    {
    	return $this->concepte->getConcepteLlarg();
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId() 
    {
        return $this->id;
    }

    /**
     * Set num
     *
     * @param integer $num
     * @return Apunt
     */
    public function setNum($num)
    {
        $this->num = $num;

        return $this;
    }

    /**
     * Get num
     *
     * @return integer 
     */
    public function getNum()
    {
        return $this->num;
    }

    
    /**
     * Set dataapunt
     *
     * @param \DateTime $dataapunt
     * @return Apunt
     */
    public function setDataapunt($dataapunt)
    {
    	$this->dataapunt = $dataapunt;
    
    	return $this;
    }
    
    /**
     * Get dataapunt
     *
     * @return \DateTime
     */
    public function getDataapunt()
    {
    	return $this->dataapunt;
    }
    
	/**
     * Set tipus
     *
     * @param string $tipus
     * @return Apunt
     */
    public function setTipus($tipus)
    {
    	$this->tipus = $tipus;
    
    	return $this;
    }
    
    /**
     * Get tipus
     *
     * @return string
     */
    public function getTipus()
    {
    	return $this->tipus;
    }
    
    /**
     * Set import
     *
     * @param double $import
     * @return Apunt
     */
    public function setImport($import)
    {
    	$this->import = $import;
    
    	return $this;
    }
    
    /**
     * Get import
     *
     * @return double
     */
    public function getImport()
    {
    	return $this->import;
    }
    
    /**
     * Set concepte
     *
     * @param \Foment\GestioBundle\Entity\ApuntConcepte $concepte
     * @return Apunt
     */
    public function setConcepte(\Foment\GestioBundle\Entity\ApuntConcepte $concepte = null)
    {
    	$this->concepte = $concepte;
    
    	return $this;
    }
    
    /**
     * Get concepte
     *
     * @return \Foment\GestioBundle\Entity\ApuntConcepte
     */
    public function getConcepte()
    {
    	return $this->concepte;
    }
    
    /**
     * Set observacions
     *
     * @param string $observacions
     * @return Apunt
     */
    public function setObservacions($observacions)
    {
    	$this->observacions = $observacions;
    
    	return $this;
    }
    
    /**
     * Get observacions
     *
     * @return string
     */
    public function getObservacions()
    {
    	return $this->observacions;
    }
    
    
    /**
     * Set rebut
     *
     * @param \Foment\GestioBundle\Entity\Rebut $rebut
     * @return Apunt
     */
    public function setRebut(\Foment\GestioBundle\Entity\Rebut $rebut = null)
    {
    	$this->rebut = $rebut;
    
    	return $this;
    }
    
    /**
     * Get rebut
     *
     * @return \Foment\GestioBundle\Entity\Rebut
     */
    public function getRebut()
    {
    	return $this->rebut;
    }
    
    
    /**
     * Set dataentrada
     *
     * @param \DateTime $dataentrada
     * @return Apunt
     */
    public function setDataentrada($dataentrada)
    {
        $this->dataentrada = $dataentrada;

        return $this;
    }

    /**
     * Get dataentrada
     *
     * @return \DateTime 
     */
    public function getDataentrada()
    {
        return $this->dataentrada;
    }

    /**
     * Set datamodificacio
     *
     * @param \DateTime $datamodificacio
     * @return Apunt
     */
    public function setDatamodificacio($datamodificacio)
    {
        $this->datamodificacio = $datamodificacio;

        return $this;
    }

    /**
     * Get datamodificacio
     *
     * @return \DateTime 
     */
    public function getDatamodificacio()
    {
        return $this->datamodificacio;
    }

    /**
     * Set databaixa
     *
     * @param \DateTime $databaixa
     * @return Apunt
     */
    public function setDatabaixa($databaixa)
    {
        $this->databaixa = $databaixa;

        return $this;
    }

    /**
     * Get databaixa
     *
     * @return \DateTime 
     */
    public function getDatabaixa()
    {
        return $this->databaixa;
    }
}

src/Foment/GestioBundle/Entity/Junta.php
<?php 
// src/Foment/GestioBundle/Entity/Junta.php
namespace Foment\GestioBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Foment\GestioBundle\Controller\UtilsController;

/**
 * @ORM\Entity 
 * @ORM\Table(name="junta")
 */

// When generetes inheritance entity comment extends ...
// http://docs.doctrine-project.org/en/latest/reference/faq.html#can-i-use-inheritance-with-doctrine-2
class Junta extends Membre
{
	/**
	 * @ORM\Id
	 * @ORM\OneToOne(targetEntity="Membre", cascade={"persist", "remove"})
	 * @ORM\JoinColumn(name="id", referencedColumnName="id")
	 */
    protected $id;

    /**
     * @ORM\Column(type="smallint", nullable=false) 
     */
    protected $carrec;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    protected $area;
    
    /**
     * @ORM\Column(type="date", nullable=false)
     */
    protected $datadesde;
    
    /**
     * @ORM\Column(type="date", nullable=true)
     */
    protected $datafins;
    
    
    /**
     * Constructor
     */
    public function __construct()
    {
    	// Valors per defecte
    	$this->carrec = 5;
    	$this->datadesde = new \DateTime('today');
    	$this->datafins = null;
    	// Hack per permetre múltiples constructors
    	$a = func_get_args();
    	$i = func_num_args();
    
    	if ($i == 1) {
    		if ($a[0] instanceof Membre and method_exists($this,$f='__constructMembreJunta')) {
    			call_user_func_array(array($this,$f),$a);
    		}
    	} else {
    		parent::__construct();
    	}
    }
    
    /**
     * Constructor from Membre
     *
     * @param \Foment\GestioBundle\Entity\Membre $membre
     */
    public function __constructMembreJunta($membre)
    {
    	parent::__construct($membre);
    }
    
    /**
     * És junta? true
     *
     * @return boolean
     */
    public function esJunta() { return true; }
    
    /**
     * És junta vigent? true
     *
     * @return boolean
     */
    public function esJuntaVigent() { return $this->datafins == null; }
    
    /**
     * Get carrec junta as string
     *
     * @return string
     */
    public function getCarrecjunta()
    {
    	return UtilsController::getCarrecJunta($this->carrec);
    }
    
    /**
     * Get info as string
     *
     * @return string
     */
    public function getInfo()
    {
    	if ($this->datacancelacio != null) return parent::getInfo();
    	
    	return $this->getCarrecjunta();
    }
    
    /**
     * Set carrec
     *
     * @param integer $carrec
     * @return Junta
     */
    public function setCarrec($carrec)
    {
        $this->carrec = $carrec;

        return $this;
    }

    /**
     * Get carrec
     *
     * @return integer 
     */
    public function getCarrec()
    {
        return $this->carrec;
    }

    /**
     * Set area
     *
     * @param string $area
     * @return Junta
     */
    public function setArea($area)
    {
    	$this->area = $area;
    
    	return $this;
    }
    
    /**
     * Get area
     *
     * @return string
     */
    public function getArea()
    {
    	return $this->area;
    }
    
    /**
     * Set datadesde
     *
     * @param \DateTime $datadesde
     * @return Junta
     */
    public function setDatadesde($datadesde)
    {
        $this->datadesde = $datadesde;

        return $this;
    }

    /**
     * Get datadesde
     *
     * @return \DateTime 
     */
    public function getDatadesde()
    {
        return $this->datadesde;
    }

    /**
     * Set id
     *
     * @param \Foment\GestioBundle\Entity\Membre $id
     * @return Junta
     */
    public function setId(\Foment\GestioBundle\Entity\Membre $id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get id
     *
     * @return \Foment\GestioBundle\Entity\Membre 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set datafins
     *
     * @param \DateTime $datafins
     * @return Junta
     */
    public function setDatafins($datafins)
    {
        $this->datafins = $datafins;

        return $this;
    }

    /**
     * Get datafins
     *
     * @return \DateTime 
     */
    public function getDatafins()
    {
        return $this->datafins;
    }
}

src/Foment/GestioBundle/Resources/views/Includes/messages-inner.html.twig
{%  if app.session.flashbag.has('inner-error') %}
<div class="alert alert-danger form-alert alert-dismissible">
	<button type="button" class="close" data-dismiss="alert">
	<span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	<ul>
{% for flashMessage in app.session.flashbag.get('inner-error') %}
       	<li><span class="fa fa-exclamation-circle fa-1x"></span> {{ flashMessage|raw }}</li>
{% endfor %}
</ul></div>
{% endif %}
{%  if app.session.flashbag.has('inner-notice') %}
<div class="alert alert-success form-alert alert-dismissible">
	<button type="button" class="close" data-dismiss="alert">
	<span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	<ul>
{% for flashMessage in app.session.flashbag.get('inner-notice') %}
   		<li><span class="fa fa-info-cicle fa-1x"></span> {{ flashMessage|raw }}</li>
{% endfor %}
	</ul></div>
{% endif %}

src/Foment/GestioBundle/Resources/views/Includes/selectoranys.html.twig
<div class="selector-anys"> 
	<h4 class="form-block-label">seleccionar exercici</h4>
   	<div class="input-group icon-container"><span class="input-group-addon input-group-addon-icon">&nbsp;</span>
		<div class="form-select form-select-inner">{{ form_widget(form.selectoranys, {'attr': {'placeholder': '' } })  }}</div>
	</div>
</div>

src/Foment/GestioBundle/Resources/views/Includes/taulajuntaseccio.html.twig
<div class="panel panel-default taula-resultats full-width-container">
	<table class="table">
		{% if edicioTaulajunta is not defined  %}
			{% set edicioTaulajunta = false  %}
		{% endif %}
		<tbody class="droppable">
			
			<tr class="fila-taula-buida" {% if seccio.membresJunta()|length > 0 %} style="display:none" {% endif %}>
				<td colspan="4"><div class="alert alert-danger">No hi ha cap membre a la junta</div></td></tr>
			
			{% if (edicioTaulajunta == true) %}
				{% for index, membrejunta in formjunta.membresjunta %}
				<tr class="item-junta-{{ membrejunta.vars.value.soci.id }} membre-junta  {% if (membrejunta.vars.value.id == 0) %} membre-junta-tmp {%  endif  %}">
					<td class="jidjunta hidden-col">{{ form_widget(membrejunta.id) }}</td>
					<td class="jidsoci hidden-col">{{ form_widget(membrejunta.idsoci) }}</td>
					<td class="jinfomembre">
						<div class="jnomsoci col-md-12">{{ membrejunta.vars.value.soci.nom}} {{ membrejunta.vars.value.soci.cognoms}}
							(soci: <span class="jnumsoci">{{ membrejunta.vars.value.soci.id|number_format(0, ',', '.') }}</span>)</div>
						<div class="jcarrecsoci col-md-6">
							<div class="input-group full-width-container"><span class="input-group-addon input-group-addon-icon"><span class="fa fa-graduation-cap fa-1x"></span></span>
		   						<div class="form-select">{{ form_widget(membrejunta.carrec) }}</div>
		   					</div>
						</div>
						<div class="jareacarrec col-md-6">
							<div class="input-group"><span class="input-group-addon"></span>
						       	{{ form_widget(membrejunta.area, {'attr': {'placeholder': 'àrea', 'class': 'form-control' } })  }}
						    </div>
						</div>
					</td>

					<td class="icon-cell icon-1x table-field-right"><a class="remove-soci-junta" href="{{ path('foment_gestio_editjunta', { 'edit': 'edit', 'action': 'remove',  'soci': membrejunta.vars.value.soci.id }) }}"><span class="fa fa-trash-o fa-1x"></span></a></td>
				</tr>
				{% endfor %}
			{%  else %}
				{% for membrejunta in seccio.membresJunta() %}
				<tr class="item-junta-{{ membrejunta.soci.id }} membre-junta">
					<td class="jidjunta hidden-col">{{ membrejunta.id }}</td>
					<td class="jidsoci hidden-col">{{ membrejunta.soci.id }}</td>
					<td class="jcarrecsoci">{{ membrejunta.carrecjunta }}<span class="jareacarrec">{{ membrejunta.area }}</span></td>
					<td class="jnomsoci">{{ membrejunta.soci.nom }} {{ membrejunta.soci.cognoms }} (soci: <span class="jnumsoci">{{ membrejunta.soci.numsoci }}</span>)</td>
				</tr>
				{% endfor %}
			{% endif %}
		</tbody>			
	</table>
</div>

src/Foment/GestioBundle/Resources/views/Includes/taularebuts.html.twig
{% if titleRebuts is not defined %}
	{% set titleRebuts = 'Rebuts' %}
{% endif %}
	
	
			<div class="panel-heading">
				<div class="row"><span class="col-md-6 blue-title">{{ titleRebuts  }}</span>
					<div class="col-md-6 text-right"><span class="total-rowcount blue-title">Total: {{ rebuts.getTotalItemCount|number_format(0, ',', '.') }}</span></div>
				</div>
			</div>
			<table class="table">
				<thead>
					<tr>
						<th class="hidrebut hidden-col">&nbsp;</th>
						<th class="check-all"><input type="checkbox"></th>
						<th class="toggle-all"><a class="show-hide-rows" href="javascript:void(0)"><span class="fa fa-plus-circle fa-1 #fff"></span></a></th>
						<th class="hrebutnum table-field-right">
							{% if rebuts.isSorted('r.num') %}<span class="fa fa-sort fa-1x"></span>{% endif %} 
							{{ knp_pagination_sortable(rebuts, 'rebut.', 'r.num') }}</th>
						<th class="hrebutpersona table-field-left">deutor</th>
						<th class="hrebuttipus table-field-left">pagament</th>
						<th class="hrebutdataemissio table-field-center">
							{% if rebuts.isSorted('r.dataemissio') %}<span class="fa fa-sort fa-1x"></span>{% endif %} 
							{{ knp_pagination_sortable(rebuts, 'data', 'r.dataemissio') }}</th>
						<th class="hrebutfacturacio table-field-center">facturacio</th>
						<th class="hrebutdatapagament table-field-center">
							{% if rebuts.isSorted('r.datapagament') %}<span class="fa fa-sort fa-1x"></span>{% endif %} 
							{{ knp_pagination_sortable(rebuts, 'cobrat', 'r.datapagament') }}</th>
						<th class="hrebutdataretornat table-field-center">
							{% if rebuts.isSorted('r.dataretornat') %}<span class="fa fa-sort fa-1x"></span>{% endif %} 
							{{ knp_pagination_sortable(rebuts, 'retornat', 'r.dataretornat') }}</th>
						<th class="hrebutdatabaixa table-field-center">
							{% if rebuts.isSorted('r.databaixa') %}<span class="fa fa-sort fa-1x"></span>{% endif %} 
							{{ knp_pagination_sortable(rebuts, 'anul·lat', 'r.databaixa') }}</th>
						<th class="hrebutimport table-field-center">import</th>				
						<th class="hrebuticon">&nbsp;</th>
					</tr>
				</thead>
				<tbody>
					{% set totalAnulats = 0  %}
					{% for rebut in rebuts %}
						{% if rebut.databaixa is not null %}  {% set totalAnulats = totalAnulats + 1  %} {% endif %}
						<tr class="row-resultat-cerca rebut-row{% if rebut.databaixa is not null %} rebut-anulat{% endif %}
									{% if rebut.cobrat == true %} rebut-cobrat{% endif %}
									{% if rebut.retornat == true %} rebut-retornat{% endif %}" >
							<td class="idrebut hidden-col">{{ rebut.id }}</td>
							<td class="check-one"><input type="checkbox" name="idrebut" value="{{ rebut.id }}"></td>
							<td class="toggle-rows"><a class="show-hide-rows" href="javascript:void(0)"><span class="fa fa-plus-circle fa-1 blue"></span></a></td>
							<td class="rebutnum table-field-right"><span class="rebutnumformat">{{ rebut.numFormat }}</span> x{{ rebut.detalls|length }}</td>
							<td class="rebutpersona table-field-left">
								<a href="{{ path('foment_gestio_rebuts', {'persona': rebut.deutor.id }) }}" title="Veure rebuts de la persona">
									{{ rebut.deutor.nomCognoms }}</a></td>
							<td class="rebuttipus table-field-left">{{ rebut.texttipuspagament }}</td> 
							<td class="rebutdataemissio table-field-center">{{ rebut.dataemissio|date('d/m/y') }}</td>
							<td class="rebutfacturacio table-field-center">
								{% if rebut.esactivitat %}
								<a class="accedir-facturacions" href="{{ path('foment_gestio_facturacions', 
									({'current': rebut.dataemissio|date('Y'), 'semestre': 0, 'active': 2, 'activitat': rebut.activitatId  } ))  }}" title="Veure facturació">
									{{ rebut.descripciofacturacio }}
								</a>
								{% else %}
								<a class="accedir-facturacions" href="{{ path('foment_gestio_facturacions', 
									({'current': rebut.dataemissio|date('Y'), 'semestre': 0  } ))  }}" title="Accedir a facturacions">
									{{ rebut.descripciofacturacio }}
								</a>
								{% endif %}
							</td>
							<td class="rebutdatapagament table-field-center">{{ rebut.datapagament is empty ? '': rebut.datapagament|date('d/m/y') }}</td>
							<td class="rebutdataretornat table-field-center">{{ rebut.dataretornat is empty ? '': rebut.dataretornat|date('d/m/y') }}</td>
							<td class="rebutdatabaixa table-field-center">{{ rebut.databaixa is empty ? '': rebut.databaixa|date('d/m/y') }}</td>
							<td class="rebutimport table-field-center">{{ rebut.import|number_format(2, ',', '.') }}€{% if rebut.escorreccio == true %}*{% endif %}</td>
							<td class="rebuticon icon-cell">
								{% include 'FomentGestioBundle:Includes:actionsrebuts.html.twig' %}
							</td>
						</tr>
						{% for detall in rebut.detallsSortedByNum(true) %}
							{% set classnocercat = ""  %}
							{% if detall.persona.id != queryparams.persona %}
								{% set classnocercat = "row-no-cercada"  %}
							{% endif %}
							<tr class="detall-rebut 
													{% if detall.databaixa is not null %} detall-anulat{% endif %}
													{% if detall.persona.id == queryparams.persona %} row-cercada{% endif %}" data-attr-rebut="{{ rebut.id }}">
								<td class="iddetall hidden-col">{{ detall.id }}</td>
								<td colspan="2" class="idpersonadetall table-field-right">{% if detall.persona.id == queryparams.persona %} <span class="fa fa-arrow-right fa_1 green"></span>{% else %}&nbsp;{% endif %}</td>
								<td class="numdetall table-field-right">{{ detall.numdetall }}</td>
								<td class="personadetall table-field-left">
									<a href="{{ path('foment_gestio_veuredadespersonals', {'id': detall.persona.id, 'soci': (detall.persona.essocivigent) }) }}" title="Veure dades de la persona">
									{{ detall.persona.numsoci }}-{{ detall.persona.nomcognoms }}</a></td>
								<td colspan="5" class="conceptedetall table-field-left">{{ detall.concepte }}</td>
								<td class="databaixadetall table-field-center">{{ detall.databaixa is empty ? '': detall.databaixa|date('d/m/y') }}</td>
								<td class="importdetall table-field-center">{{ detall.import|number_format(2, ',', '.') }}€</td>
								<td class="rebuticondetall icon-cell">
									{% if detall.esEsborrable == true %}
									<a class="simple-anuladetall" href="{{ path('foment_gestio_anulardetall', ({'id': detall.id}|merge(queryparams)) )  }}" title="Anul·lar línia del rebut"><span class="fa fa-times fa-1 red"></span></a>
									{% endif %}
								</td>
							</tr>
						{% endfor %}
						{% if rebut.escorreccio == true %}
							{# nova fila detall amb la correcció #}
							<tr class="detall-rebut detall-correccio" data-attr-rebut="{{ rebut.id }}">
								<td class="iddetall hidden-col">&nbsp;</td>
								<td colspan="2" class="idpersonadetall">&nbsp;</td>
								<td class="numdetall">&nbsp;</td>
								<td class="personadetall">&nbsp;</td>
								<td colspan="5" class="conceptedetall table-field-left">Correcció</td>
								<td class="databaixadetall table-field-center">&nbsp;</td>
								<td class="importdetall table-field-center">{{ (rebut.importcorreccio - rebut.importsensecorreccio)|number_format(2, ',', '.') }}€</td>
								<td class="rebuticondetall icon-cell">&nbsp;</td>
							</tr>
						{% endif %}
					{% endfor %}
		    	</tbody>		
			</table>
			<div class="panel-footer">
				<div class="row">
					<input id="total-rebuts" type="hidden" value="{{ rebuts.getTotalItemCount|number_format(0, ',', '.') }}">
					<input id="total-senseanulats" type="hidden" value="{{ (rebuts.getTotalItemCount-totalAnulats)|number_format(0, ',', '.') }}">
					{% if rebuts.getTotalItemCount > 0 %}
						<div class="check-all"><input type="checkbox"></div>
						<div class="col-md-3 footer-left footer-left-with-check col-xs-6">
							<div class="form-select form-select-inner selector_accions">
								<select id="selector_acciomultiple" placeholder="amb seleccionats...">
									<option value="0">amb seleccionats...</option>
									<option value="{{ path('foment_gestio_cobrarrebut', queryparams ) }}">Domiciliacions cobrades</option>
									<option value="{{ path('foment_gestio_retornarrebut', queryparams )  }}">Domiciliacions retornades</option>
									<option value="{{ path('foment_gestio_anularrebut', queryparams )  }}">Anul·lar seleccionats</option>
								</select>
							</div>
						</div>
						<div class="col-md-3">
							<div class="accions-massives">
								<a href="javascript:void(0)" title="enviar amb els rebuts seleccionats"><span class="fa fa-check-circle-o fa-1 green"></span></a>
							</div>
						</div>
						{% if rebuts.getTotalItemCount > rebuts|length %}
							<div class="col-md-6 text-right">
								{#<a class="veure-tots" href="{{ path('foment_gestio_rebuts', ({ 'tots': 1 }|merge(queryparams)) )  }}" title="veure tots">mostrar tots<span class="fa fa-list fa-1"></span></a>#}
								<span class="navigation blue-title">Pàgines: {{ knp_pagination_render(rebuts, null, queryparams) }}</span>
							</div>	
						{% endif %}
					{% else %}
						<div class="alert">
							<div class="alert alert-success">cerca sense resultats</div>
						</div>
			    	{% endif %}	
				</div>
			</div>	
			
	<div class="import-recarrec"> 
	 	<div class="form-block row">
	 		<div class="col-md-6">
	   			<h4 class="form-block-label">import del recàrrec</h4>
	   		</div>
	   		<div class="col-md-6">
   				<div class="input-group input-row-right">
	        		<input type="text" id="form_recarrec" value="{{ constant('Foment\\GestioBundle\\Controller\\UtilsController::RECARREC_REBUT_RETORNAT')  }}" class="form-control form-control-right rebut-recarrec form-control-value" placeholder="recàrrec" required="required">
	        		<span class="input-group-addon input-group-addon-icon"><span class="fa fa-eur fa-1x"></span></span>
	    		</div>
	    	</div>
	    	<div class="col-md-12 hr"><hr/></div>
	    	<div class="col-md-12 llista-rebuts">
	    	</div>
	    </div>
	</div>